# -*- coding: utf-8 -*-
"""Minor project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cpYn_lxgPw7TLeQtLuVWMKeMH4k92As
"""

#3Q
import numpy as np

def get_expenses():
    n = int(input("Enter number of days: "))
    expenses = []

    for i in range(n):
        amt = float(input(f"Enter expense for day {i+1}: "))
        expenses.append(amt)

    return np.array(expenses)

def analyze_expenses(arr):
    total = arr.sum()
    average = arr.mean()
    highest = arr.max()

    print("\n----- Expense Summary -----")
    print("Total Expense:", total)
    print("Average Expense:", average)
    print("Highest Expense:", highest)

    if average > 1000:
        print("Warning: Your average expense is very high!")

# Main Program
print("DAILY EXPENSE TRACKER")

expense_array = get_expenses()
analyze_expenses(expense_array)

print("\nThank you for using Daily Expense Tracker!")

#4Q

import numpy as np

def get_numbers():
    n = int(input("How many numbers? "))
    nums = []

    for i in range(n):
        val = float(input(f"Enter number {i+1}: "))
        nums.append(val)

    return np.array(nums)

while True:
    print("\nSMART CALCULATOR")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Power")
    print("6. Modulus")
    print("7. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 7:
        print("Thank you for using calculator!")
        break

    numbers = get_numbers()

    if choice == 1:
        print("Result:", numbers.sum())

    elif choice == 2:
        result = numbers[0]
        for i in range(1, len(numbers)):
            result -= numbers[i]
        print("Result:", result)

    elif choice == 3:
        result = 1
        for i in numbers:
            result *= i
        print("Result:", result)

    elif choice == 4:
        result = numbers[0]
        for i in range(1, len(numbers)):
            if numbers[i] == 0:
                print("Division by zero not allowed!")
                break
            result /= numbers[i]
        else:
            print("Result:", result)

    elif choice == 5:
        print("Result:", numbers[0] ** numbers[1])

    elif choice == 6:
        print("Result:", numbers[0] % numbers[1])

    else:
        print("Invalid choice!")

#5Q

import numpy as np

def get_marks():
    n = int(input("Enter number of students: "))
    marks = []

    for i in range(n):
        m = float(input(f"Enter marks of student {i+1}: "))
        marks.append(m)

    return np.array(marks)

def analyze_marks(arr):
    total = arr.sum()
    average = arr.mean()
    highest = arr.max()
    lowest = arr.min()

    print("\n----- Marks Analysis -----")
    print("Total Marks:", total)
    print("Average Marks:", average)
    print("Highest Marks:", highest)
    print("Lowest Marks:", lowest)

    if average >= 85:
        grade = "A"
    elif average >= 70:
        grade = "B"
    elif average >= 50:
        grade = "C"
    else:
        grade = "Fail"

    print("Grade:", grade)

# Main Program
print("STUDENT MARKS ANALYZER")

marks_array = get_marks()
analyze_marks(marks_array)

print("\nThank you!")

username = input("Enter username: ")
password = input("Enter password: ")

if username == "admin" and password == "1234":
    print("Login Successful")

elif username == "admin" and password != "1234":
    print("Incorrect Password")

else:
    print("Invalid Username")